export const FETCH_PRODUCTS_STARTED = 'FETCH_PRODUCTS_STARTED';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_BRANDS_STARTED = 'FETCH_BRANDS_STARTED';
export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';

export const SELECT_PRODUCT = 'SELECT_PRODUCT';

export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_BRAND = 'FILTER_BRAND';
export const FILTER_MAX_PRICE = 'FILTER_MAX_PRICE';
export const RESET_FILTERS = 'RESET_FILTERS';
