version: '3.8'

services:

  workspace:
    image: ${NODE_IMAGE}
    working_dir: /var/www/react
    volumes:
      - ../:/var/www/react
    ports:
      - "${REACT_PORT}:3000"
      - "${VITE_PORT}:5173"
    tty: true
