FROM node:11-alpine

WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
COPY ./.babelrc ./.babelrc

RUN npm install

COPY . .

EXPOSE 5000

CMD ["npm", "start"]
