export const FETCH_PRODUCTS_STARTED = 'FETCH_PRODUCTS_STARTED';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_BRANDS_STARTED = 'FETCH_BRANDS_STARTED';
export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';
