FROM node:11-alpine

RUN yarn global add json-server-relationship
RUN yarn global add knex

WORKDIR '/app'
COPY ./package.json ./package.json
RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "run", "start"]
